### ISSUE TITLE
provide rdo-release-master.rpm

### ISSUE THREAD

**Issue by rlandy** [redhat-openstack/rdo-release#10]
Please see https://bugs.launchpad.net/tripleo/+bug/1780780 for the problem discussion. The bug description is copied below for tracking:

Tempest test test_network_basic_ops running on master with scenario007 and scenario008 jobs fails with networking/connection issues:

http://logs.openstack.org/53/579653/3/check/tripleo-ci-centos-7-scenario008-multinode-oooq-container/5e299dc/logs/undercloud/home/zuul/tempest/tempest.html.gz

The problem stems from that fact that we now set up br-ex using pre.yaml from zuul-jobs which relies on a released version of openvswitch:

https://github.com/openstack-infra/zuul-jobs/blob/master/roles/multi-node-bridge/vars/RedHat.yaml#L4

https://github.com/openstack-infra/zuul-jobs/blob/master/roles/multi-node-bridge/tasks/common.yaml#L21

The role defaulted to the ocata version - hence the incompatibility with master deployments.
I was able to get the scenario007 to pass in my local reproducer environment when using the released queens version of openvswitch.

The methodology here is problematic. If we plan to test TripleO integration with OVS, and we only bring in the change with the run playbooks, the pre playbooks will set up with the released version and we will never test what is being changed - or even what is in the master repos.

When you used a role in tripleo-quickstart-extras to create br-ex, an updated OVS version was already available to be used in the test.

**Comment by apevec** [comment]
https://review.openstack.org/580518 is switching openstack-infra to use centos-release-openstack-queens
and as noted in that review this OVS could be and afaik is updated by the tripleoci, problem might be 2.6 -> 2.9 upgrade steps are missing i.e. restart ovs service since this is not done anymore by the RPM %post to avoid uncontrolled data plane outages during updates.

**Comment by apevec** [comment]
IIUC request here was actually to provide rdo-release-master.rpm but this doesn't actually help with the issue reported in linked LP

There are no plans to provide rdo-release-master.rpm until we have a clear use-case.
