### ISSUE TITLE
EPEL is EVIL

### ISSUE THREAD

**Issue by trown** [redhat-openstack/rdo-release#3]
The ceph packages are the only real need for EPEL at this point, but there are multiple places where EPEL is either checked for (instack-virt-setup), or gets installed in images (diskimage-builder).

I would like to get all of that fixed up for Mitaka release, but in the meantime, users of the production repo keep hitting the issue with broken hiera from EPEL.

One solution would be to add a priorities to the production repos, and add yum-plugin-priorities as a dep of the rdo-release rpm.

**Comment by bjames301** [comment]
I agree this needs to be address as currently leaving EPEL enabled without Hiera\* disabled breaks the undercloud install.

**Comment by apevec** [comment]
EPEL is now removed in TripleO https://review.openstack.org/336551 https://review.openstack.org/347499 https://review.openstack.org/347513

**Comment by trown** [comment]
also https://review.openstack.org/#/c/368974/ :)

**Comment by apevec** [comment]
Disabling EPEL is recommended in docs http://docs.openstack.org/mitaka/install-guide-rdo/environment-packages.html#prerequisites should we still look at hacks with yum priorities in rdo-release rpm?

**Comment by apevec** [comment]
We are not going to mess with yum priorities in default release repos.
