### ISSUE TITLE
Can/should we add centos-release-ceph-jewel to rdo-release-newton ?

### ISSUE THREAD

**Issue by dmsimard** [redhat-openstack/rdo-release#9]
The release of Ceph that we test with Newton is Jewel.
Should we ship it ?

**Comment by apevec** [comment]
Looks like consensus from #rdo is: NO.
Ceph is optional and feedback we got after adding it to centos-release-openstack-mitaka pointed to some issues e.g. mitaka depeds on ceph-hammer but some users made it work with ceph-jewel so forcing Hammer on them was bad.
Keeping rdo-release without Ceph repo dependency gives them a workaround.
